# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  app.secure_cookies: false
  app.jwt_ttl: 86400

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  App\:
    resource: "../src/"
    exclude:
      - "../src/DependencyInjection/"
      - "../src/Entity/"
      - "../src/Kernel.php"

  App\Service\ResendService:
    arguments:
      $apiKey: "%env(RESEND_API_KEY)%"

  App\Service\EmailService:
    arguments:
      $fromEmail: "%env(EMAIL_FROM)%"
      $appUrl: "%env(APP_URL)%"

  App\Security\JwtCookieManager:
    arguments:
      $cookieName: "AUTH_TOKEN"
      $secureCookie: "%app.secure_cookies%"
      $tokenTtl: "%app.jwt_ttl%"
    tags:
      - { name: kernel.event_subscriber }

  lexik_jwt_authentication.handler.authentication_success:
    alias: App\Security\JwtCookieManager
    public: true
